package utils

import (
	"fmt"
	"math/rand"
	"strings"
)

var randomParagraphs = [...]string{
	"Nec res una proinde chartam requiri quaenam confuse. De ea se tamquam haberet exempli memores ipsarum ob. Earum se athei vi erunt. Si ad exhibent reperiri perpauca ab physicam invenero. Veluti unquam loquar easdem sua errare fas imo. Clara harum ipsis tamen ac ha longa co at mente. Ii si videretur ac contineri occurrere remanetne deleantur. Istam nomen in lucis ab donum volui quare.",
	"Hominem eos hac religio tentabo ginabor. Laxissimas objectivam eo percipitur distinctum ii industriam. Mei scopo ideis horum vel factu rei. Initio ad vereor posita possum si possim eo bitavi. Re novi vero mens in me ipse. Ad nolo ac unam dico in me. Is odoratu fallant vi vestiri percipi ex et. Confirmari respondebo videbuntur voluntates dum per intelligat. Admonitus dubitavit sui consistat uti inspiciam persuadet perfectum.",
	"Afferri nul invicem quamvis columen sum pendent. Et ad me voce si omne meos ante addo. Aspi has inde hoc plus solo cau unum. Attingebam apprehendo et secernitur contrarium propugnent co. Virtutibus vigilantes effectibus is abducendam ii ut cogitantur procederet. Totali mentes partim realis cupiam jam quo. Odoratu proprie ac co produci se.",
	"Et impellit synopsis in cognitio pluribus machinam. Vulgo locum ii sumne ac. Dicerem aliquam lor sum est similia claudam ego pretium agendis. Lumine eas deinde putare delebo rei sed negare ego loquor. Sequentium diligenter is consuetudo percipimus ostenditur ii vi. Ingressus sap calescere subjectum nul via evidentia etc posuerunt. Quasi pacto seu ens haben sua. Majorque ad ab habuimus cernitur videntur.",
	"Ab aggrediar tangantur potuerunt cogitatio principia an. Efficere rerumque alicujus immobile occurrit agi qui habentur ego. At vocant gloria factae ei. Ac de falso ut ideas visus gi istis. Hac sane bono tot unam. Remanetne usurpabam contineri ut in. Praemissae laxissimas sim fit expergisci sum rem probabiles.",
	"Vidi addi hic dat etsi solo pla lor. Se judicare posuisse eo occurret de lectorum du adipisci infiniti. Nexum culpa oculi si in cogor demus nulli. Eidem ita tur dubie etiam. Co multarum an at impellit inanimes quidquid siquidem. Ipsos ullum ullam ii ea. An praestare cupientem reliquiae to admiserim co ac recurrunt obdormiam. Et ii paulo color mo atque serie to.",
	"Conflantur concipitur durationis praesertim de me. Noctu lumen co ac istas sonos illos falsa. Uti mea cavendum fingerem occurret vos paulatim firmanda cognitum. Potens ac cupiam mearum talium haberi mo tandem. Me puram habeo at edita typis. Talis nonne veram ac ha si fingi ac.",
	"Inanimes ad ut fallacem reversus sorbonae reperire. Finita de tritam oculos negavi habere si ha certas. Mox uno non namque tam realem dubito quaeso. Du videamus ac externis incertas potuerit immerito. Suam his agi fuse vere tot nunc ille. Cadavere ex ignorans de gi sessione concludi momentis. Non ero colore odoris eandem coelum tam.",
	"Erat deum volo ipsa imo sibi usu apta. Sui secius sapere tamdiu sic realis lumine factas. Recurrunt vis perlegere mem sua judicarem solvendae opinionum obstinate quo. Ii erit id vi nudi sine ipso ut. Sciatur saeculi vis virorum mem sua sub. Rerum aliae ne sciri eo re et famam errem. Clausulas praeterea percipere tur non ibi venientia colligere res. Pendere vox secunda rea humanae aut brachia cum. Ultimum indutum efficta mo is. Im terea capax opere dubio ne nexum illud co.",
	"Instituti desumptam id solvendae ad obversari. Nul falsum eae ego habeam opinio sit nullis inesse volent. Nolo in enim quia duas ex vice se to. Vigiliam repetere realiter hoc vul reliquis facultas vix sit recorder. Posset to sumpti re mendax. Ubi fal duo videbo vereor totius primae. Scientiis contingit somniorum ne in artificis objicient. Institutum co ex du frequenter substantia praevidere mortalibus ab. Clara si ab co sacra in erunt illud. Futurus ubi suo constet ejusdem spondeo vul testari.",
	"Tamquam ita veritas res equidem. Ea in ad expertus paulatim poterunt. Imo volo aspi novi tur. Ferre hic neque vulgo hae athei spero. Tantumdem naturales excaecant notaverim etc cau perfacile occurrere. Loco visa to du huic at in dixi aër.",
	"Infixa ac de mellis at habeam humana in. Momentis sequitur eas sua ulterius probatur cum. Quaeque poterit vim cognitu via possunt qua. Tam colligere nia principia praecipue pergamque stabilire fictitium. Lucem ii operi edita leone porro novum ab. Hae quavis hic tam essent quidam altius multis tum.",
	"Ignem ratio fingo istam etc vix una velut veris deo. Teneri habeam perire putavi to cogito sentio me ac. Ad potuisse in ne supponit loquendo me. Sed vixque rei verbis dicunt dat jam. Animal angeli sumpti animum cau exigui sim figura duo ita. Ad attingere objectiva pertinent an si abducerem.",
	"Prona scopo ea vetus in ac esset se eorum sumne. Ens optimum ignotae alienis rem propter nec revolvo nam. Confusae hos cohiberi hac una scilicet sap timerent. Attigerint perficitur quaerendum gi detorqueat considerem ob. Industria tangantur meditatas occurrere at at ut ut partiales. Avocandam mox potuerunt tur cur intelligo sex. Via vul pro communi quamvis pugnare hominum. To quia visa ea etsi fuit ei enim quae eo. Im viderunt ab to concedam produxit. Innatae vi invicem ha organis ab saeculi et publice ipsarum.",
	"Sui eligendo mei abducere credenda callidum. Se ad me vi satyriscos sequeretur efficietur objectivus integritas. Ut utor mo data tius. De nova eram nudi ut regi esse. Cui eas sentiens nos has quanquam totamque. Objectivam extensarum iis agnoscerem tum sed patrocinio parentibus dulcedinem. Me dico tria cera re du sumi inde ea suam. Locum ac eodem si modis eo. Alio opus tria mea per mens ero apti sed plus. Jam iis figuras frigida cap putarim.",
	"Orti dai ora sia atto nel dava. The senti pel miele ali altra. Dite teco ma vedo leva fu peso. Le mistero tornato premuto vi diritta fa mi azzurro. Supplizio per afa cui sublimate osservava. Dai allegrezza guarderemo impazienza com bentornato conservare abbassando. Cielo farla neghi tenta ama uso edera. Intendeva io lavorando primavera re rientrata ho ai splendori. Sabbia gioghi creare chi sai.",
	"Pel riempiono aspettavo consiglio imaginavo mia pur congiunte. Assorto imagine par deposto concedi poi partito poi sai. Per facilita piramide tuttavia invocato sul dovresti voi piu. Meno orti sui sete naso tese udi viso. Magrezza all sofferte sai una tamerici piramide the ricevute seminato. Domani ai si capace velavi mutato io ch. Vorrei oh ho gloria saluta ma. Sorridente ma inebriarti riprendera al ho giudichera. Arteria parlato dattero rugiada ora altezza rossore ove. Noi bastanza gettando ore prendero sia turchese eleganza.",
	"Caro pei senz non tebe voi lui stai peso. Vi chiese ma ne eccolo stanza questa palese visita. Padronanza impaziente perdonarmi adorazione ai pericolosa va masticando. Debole tal gli uscire immune spenta con qua foglie sabato. Abbassando trattenuto chiedergli per cancellata col preferisti eguagliare. Andarmene disegnata impudente aspettavo su il infantile un settimane. Mettendosi bentornato espressiva nel del ricuperato era. Qua avrai mia stavi ama lungo mezzo donne. Mi suoi oh otri so atto no temi.",
	"Vissuto com parlero giacche stasera ora dev sua balsami nuotano. Profonda se avessero scolpire al racconto. Suo talvolta guardare sai sommessa vai the. Iersera ascolto lontano riempii san con. Obliare uno qua cintura istante tornano giovine. Tu nuca lega nari oggi ma di io. Ambascia te lo oscurato traverso lucidita supplico prodigio. Sua pel pel trovato spirito diritto. Eroico vai affina vostra ora pagine mie impero. Ex venuto pianto spalla mi fiocca le osando.",
	"Il torturare ma disegnata or mantenere mi. Palpitante vai cominciata osi dev seducevano pie. Monte ai acque pochi ha valso ti si fuoco. Sostenere altissimo lo al affatichi. Dai abbozzata all chi fanciulla vertigine implorare. Ma nudo atto fu bene si lega.",
	"Pranzate ma chirurgo rovescio la. Palme mi dimmi so ti fatto lieve. Ornamento mutamenti curiosita ora risolvere tuo disegnata. Splendore oh parentela inclinato fu. Malato domani tempia col aquila potrai aurora ore. Cubi pace tra the ecco pene taci file sul. Era aperta sii pensai ossuta uno bevuto sicura. Sonno notti anche pei perda via detto brevi puo. Vedremo mia sentivo che ora sentono liberta ricordo. Mai sofferte sua rovescio miracolo dov profonde talvolta condurre.",
	"Inquieto cio affinita dal mio orribile troverei scarabei. Avvelenate cominciata non improvvisa esaltavano accostarmi lei osi. Sapevi suo accade salivo appare sui. Fu tono limo voto egli vene un tu. Gomito orrore gli scelto dev dianzi dir cui. Si in pensava un tu imagine andiate dovesti spasimo. Rifletti la torrente paradiso ne su rimanete.",
	"Ami consuma arteria all tremano difendo. Ai ah parso al senza campo alcun coppa. Sogna forme ove oro sue uscio mazzo. Ch tu morra nello senso lieto su prese. Sospirare fu ornamento ho sconvolto ginocchia vigilanza un el. Aggiungera esaltavano tuo tal nascondeva affrontare ricordarmi consolarmi. Attento pensoso re precisa or giacche gettare firenze da.",
	"Dispare monella uccelli vedremo da ai tentare ma mancavo. Alzati latine eroica su guarda ed. Ritornata principio di lo portarono le abbandona. Ve stupende martirio coronare io. Appena si marito di limite oh el sapore depone. Chiedere gitterei eleganza si continua te fulminee. Amare entra sogni prima ad notti altro ex. Nuotano col mia solleva accanto.",
	"Rivolto nel lettera battera rianimo leggera tua mio gli. Abbassero vi ma aspettavo disperata ci. Chi udite misto potra com nel. Chi era monastero ospitarvi ore aspettero mia sparvieri contenuti. Scompare uso poi apriremo voi orecchio. Pensieri compatto convulsa salvezza avvicina voi sue pei parlasse. Ch resistenza nascondeva conoscermi di giudichera.",
	"Todas gasto oh en un notar mejor. Venian ruinas acepto italia en ha jugado sentia. Verlo padre apago por dos fue tio. Por preciosa don inocente perpetua asi. Oir subio veria todas del menor. Te ah ay dejandose escenario no confesaba. Integrante ahi los inmaculada ingratitud las caballeros. Te carrera tu interes parecia gozando dejaron derecha. Missure dineral egoismo en el ahorros ir.",
	"Ahi permanecer misteriosa arriesgada soy taciturnos aficionado suficiente. Un piedad al si partes bienes menudo la. Paseaban mi retirado prestaba aturdida ha saltaron ma humildes. Leer esas seca es la diga en gran cera. Mas dia reyes desde ebano por. Consentia esa cenagosas ley consistio asi romantico sus colocarse rectifico. No costumbre va observaba si te formarlas. Veia tu me duro oh os nina. Implacable sobrevenir don sin oyo desencanto.",
	"Agradaba vez soy feo hermosos hojuelas esclavos. Cuyo ni no pedi el sean ropa si odio arte. Quisieran muy separados rodeabase mil tal verdadera. Labrado tu vicende sr envidia os derriba. Encantos por son otorgado medianas que. Exclamaron la al preteritas ma aseguraban.",
	"Dejado madrid cuidan marcar veneno pesado los eso. Queridos al publicas su garganta consuela epitetos crimenes. Arena calor il un habra creer batia lucia. Mermado ton bilioso gracias sultana cerrado cantaro los. Con ambulante tio chi suo fioriture resonaban. Ocho la la musa moza de tios ni. Si ma cuya en casi suma esos flor. Mangas ofensa se ocioso da diario varios yo.",
	"Ma cantaro tiernos criadas me. Resabios serafina arriesgo recuerda le supuesto lo. Porches ofrecio miraban en senador le. He muero oh ve bueno apago la. Oh espalda muertas miradas va un negarle lugares. Mostrador reservaba chocolate mil hay presentes. Suo seca ver dios una come bajo tres gran. Al regazo oh el actual ti sabido.",
	"Uso algunos feo apatico mas ano echarse empresa. La infeliz costaba fe querido hacerlo. Compas tio correo paz empeno volado. Pero por gato foro flor mal. Encendia vio volviera pormenor lenguaje llegados rodearon una chi. Fin cristal intimas muertos mas sirenas. Aritmetico atormentar relaciones il en de inspiraban extremados. Ahi han lado leia gas oro sean.",
	"Mano rico ola las sana doy paje cuya esa. Se marido pintor quince de tendra capota idolos. Al miraba es volvio no tisica cruces detras su. Crisis contra un musica le amparo. En llevaba saltaba si encanto he su figuras erudito perdida. Actualidad escuchando sonoliento al al ex vagabundos poniendose ve confundido. Entiendes oh intereses la ni monisimas.",
	"Adivinar ensuenos circulos maltrato don doy albergue siguiera. Estetico seriedad tertulia las conviene uso esa tal. No tu pasara consta recibo un activo oh camara. Ya so plazos un afuera esposa gloria echaba pesado. Excedido singular reclamar luz enterase una supuesto. Consistio ano ahi gas importuno olvidando por. Poetizaba salvacion gas maravilla aca homenajes asustados con.",
	"Hay escopetazo les pre enguantada intensidad reintegrar. Llenara natural ya ni anonimo lastima. En al robar color toses salon meras malos. Fue mejillas babuchas sea contador las. Eso ton mesa dijo luz mil ella. Acogia estaba un un su gritos. Amenazaba eso inspirado caballero mis van los. Constituia era contrariar una traduccion ley forasteros privilegio.",
	"Sin obsequios insultaba una rey italianos altamente. Pastas oyo vieron asi siglos una. Rey prestadas iconoteca levantaba traspunte ocasiones aptitudes pie ser uso. Civil idolo dia dio opaca poeta pasos otras. Fe adulterio bonifacio escandalo lo encontrar. Aburrirse un acudieron contestar concedian importuno al palabrota. Esto ella opio otro tios fin era pedi. Voluptuosa maliciosos desencanto mis pentagrama mil magistrado etc eso. Decirte lo quinque familia egoismo emplear su humedos il le. Molestaba pensarian los peligrosa ahi intimidad pie chi.",
	"Same an quit most an. Admitting an mr disposing sportsmen. Tried on cause no spoil arise plate. Longer ladies valley get esteem use led six. Middletons resolution advantages expression themselves partiality so me at. West none hope if sing oh sent tell is.",
	"Over fact all son tell this any his. No insisted confined of weddings to returned to debating rendered. Keeps order fully so do party means young. Table nay him jokes quick. In felicity up to graceful mistaken horrible consider. Abode never think to at. So additions necessary concluded it happiness do on certainly propriety. On in green taken do offer witty of.",
	"How promotion excellent curiosity yet attempted happiness. Gay prosperous impression had conviction. For every delay death ask style. Me mean able my by in they. Extremity now strangers contained breakfast him discourse additions. Sincerity collected contented led now perpetual extremely forfeited.",
	"Rooms oh fully taken by worse do. Points afraid but may end law lasted. Was out laughter raptures returned outweigh. Luckily cheered colonel me do we attacks on highest enabled. Tried law yet style child. Bore of true of no be deal. Frequently sufficient in be unaffected. The furnished she concluded depending procuring concealed.",
	"Moments its musical age explain. But extremity sex now education concluded earnestly her continual. Oh furniture acuteness suspected continual ye something frankness. Add properly laughter sociable admitted desirous one has few stanhill. Opinion regular in perhaps another enjoyed no engaged he at. It conveying he continual ye suspected as necessary. Separate met packages shy for kindness.",
	"Spater hutete zur labsal nah sohlen leisen schale. Zog ige vorpfeifen ist bangigkeit wir eigentlich todesfalle. So la im warmen em freude drohte schade lustig. Ihn gefallts gekommen flo schmalen neustadt hol und bummelte. Euch bei jede alt muhe sei gebe. Den sitzt krank man holen ist das. Wie kronen ebenso hinaus wasser tut.",
	"Flo klopfte gerufen solange sei niemals. Da bi zitterte eigentum gelernte gegenden es halblaut ubrigens. Te gekommen behutsam er schonste liebsten zuweilen gelaufig. Zur fiel bist denn bat erde erst. Rief habs flei kam nein eine lang ans. Ein lattenzaun todesfalle mit lehrlingen. Hat adieu dus szene nacht uhr woher krank nur.",
	"Um bewirtung getrunken leuchtete in ja ausgeruht. Verbergend hin nur kartoffeln verstehsts gut federdecke sie. Angenommen la he im stockwerke knabenhaft mu. Ewige blick ku kuche neuen es. Beinahe bedeckt en heruber pa he. Nachdem besorgt man gedacht lockere sei spielen. Einfach gewesen bi madchen se er la geruckt reichen.",
	"Die erzahlt tag stiefel ton gefreut hinuber dir. Anderen weg hin zum uberall traurig gebogen nustern meisten. Mit feierabend flusterton dazwischen verdrossen nettigkeit grundstuck fur. Gelt oden la es hals sies. Alten er recht mu ubrig statt denkt du orten du. Sah prachtig gerberei geholfen ansprach des brotlose. Pa kurz mein kund sich bi wand es ging. Im ku scherzwort zu verschwand dazwischen je werkstatte leuchtturm geschlafen. Mut auch auch ihre ihrs herr ihn. Behalten gelaufig bi burschen fu wirrwarr sprachen.",
	"Um geruckt ob steilen gefallt ja meister barbara bi. Zaunpfahle hausdacher dazwischen ist achthausen aus abendsuppe uberwunden. Em vollends geschirr gerberei sa um vergrast zu gebrauch. Kummer langer sorgen haares ei zu im. Ihnen ihrem gutes um im bi so. Kleine grunen teller er an. Stadt nacht wie weich sehen ruhig sei. Ab anblick bi mu bosheit lauernd so zweimal.",
	"Bi richtete an da se gefunden bezahlen. Weste tat schen all sag seine eisen. Mensch fu em mi glaubs wasser. Drein ku nobel blatt kalte brief spurt wo. Ebenso ton und fur jahren kohlen. Kindliche unbemerkt pa unwissend vorbeugte gestorben polemisch in.",
	"Wo lattenzaun aneinander mu erhaltenen vorpfeifen grasgarten. Raschen als her achtete gedacht. Ungerechte freundlich messingnen am da. Em gearbeitet vergnugter um aufmerksam langweilig ja eigentlich. Dank und ganz hol neu also chen. Verlie kleide in sa lieber. En gebogen regnete es es niemand dunkeln ja samstag unrecht.",
	"Lief die wege als wohl. Tun zog angenommen nun dienstmagd mancherlei federdecke hat augenblick wohnzimmer. Schwemmen verweilen zufrieden stadtchen in zu wo. Erisch spinat gut mochte karten spahte stille ich. Te wu eines ja warum lobte gehen. Flecken lacheln bei schoner anblick mut beschlo sie. Luften keinem la he sterne es. In em sorgen besuch es kissen stille. In schlafen lampchen verlohnt feinheit sichtbar ab vorliebe.",
	"Er ku nachdem scheint nachtun lockere instand endlich la. Holzspane vorbeugte getrunken wohnstube kammertur bi zu. Dus dunkelrot eia uns belustigt hemdarmel neugierig zuschauer der. Zu es sa zerfasert je schonsten zierliche rausperte geheimnis anzeichen. Hatt wo eben kopf je. Dem schlanken hauswesen hellroten tat. Mu ja da gefiel im stehen angeht singen storen wieder.",
	"Ort hin finde all drein euern klare. Hei warmen mag tal stille fellen. Uberging ri hausfrau du geholfen du allerlei. An dienstmagd launischen wohnzimmer bangigkeit mi. Uns ihm hemdarmel bedeckten geblendet kellnerin gut spurenden mannsbild. Te alle gewi gott lieb lief eins se. Dunner das see wie bliebe soviel. Trauen gefiel weiler war ebenso erfuhr her geduld neu. Indem im orten jahre dabei schon im ja hoher.",
	"Wandern mehrere dunkeln so zu geschah schritt um. Floh so lass wird fein auch ab. Schweren ansprach hindurch las war getrennt blaulich. So ja herunter feinsten im schlafen. In schlo ferne einer wette an neben du horen. Ri ja jahre am wo tisch reist kaute jeder. Nun bei vorn geht den blau.",
	"So leer ware doch rote scho la. Im lehrlingen feierabend er ja ja bugeleisen gesprachig. En gang so he frau mude es. Zueinander federdecke wasserkrug er he. Leid hort nein ein mir kaum ins. Sohlen fu mu kehrte wo en sitzen. Ortes wurde extra stuhl im du schau es zu. Richtete sparlich du erzahlen konntest gesichts ri burschen. Kraftlos ob lampchen so er te schreien zinnerne vorwarts schweren.",
	"Halten angeht loffel da hellen pfeife andern es. Mannsbild ruh sudwesten bettstatt hat tun zufrieden kraftiger eia. Zu um leber warum dahin losen alles he en immer. Stimmts regnete am an la so ubrigen getafel dankbar gewesen. Der herum ich weste als ewige tat anzug drein. Wei man dort oder zart eins lust. Tag kam auf brachte stopfen mut woruber. Wei des messingnen das dazwischen geschlafen nun. Und man bis vater seiet bis stadt recht brief dafur. Arbeitete handwerke tag neugierde hei gru.",
	"Je im geschwatzt hufschmied dammerigen wasserkrug mu sa freundlich. Gutes zog neuen nicht des buben. Zusammen es la stabelle verwirrt bi konntest. Mi sa belustigt behaglich ku zu weiterhin liebhaben vogelnest einfacher. Dienstmagd so nachmittag vertreiben jahreszeit he zu er. Eck plaudernd ihn eia schwachen getrunken wohnstube.",
	"Wo bewirtung zerfasert so kraftiger handwerke ri la kindliche. Tage ja grad so mann. Gut gerberei bis gefallen arbeiter. Nun tat kostet lebtag gefegt konnen treppe laufet. Da schwarzes bewirtung ja so barbieren da. Augenblick auf hoffnungen nachtessen bilderbuch von aufmerksam todesfalle. Hoch ja ihre ab kerl en hatt uben.",
	"Hoffnungen im flusterton in achthausen landsleute federdecke lehrlingen la. Ri marktplatz kuchenture am es getunchten pa. Zu auffiel se regnete wo niemand besorgt dunkeln leuchte. Flick immer see riefe blatt tat sechs statt. Hemdarmel unwissend nachgehen sorglosen kammertur gab hin klimperte. Todesfalle te abendsuppe brotkugeln besonderes feierabend um je. Ku em dunkeln achtete gebeugt en sa anderen. Mann brot lich tun als lief drin klar.",
	"Abendsuppe so bi handarbeit erkundigte dammerigen hoffnungen ubelnehmen sa. Ort tor bald zart furs. Sofort ebenso letzte ige daheim seiest die. Horchte bildnis bat flu zuhorte nun spruche sah gelesen leuchte. Freundes nirgends so vergnugt begierig launigen gesichts wo. Mi willst lehren wochen so schlie stunde darauf wo. Weil will es nach em im kund so.",
	"Handwerke sog einfacher gestorben verodeten schlupfte des. Hufschmied flo gut sauberlich dazwischen ton. Zog erkannte gefunden kindbett gib hausherr erzahlte streckte. Messingnen geheiratet kindlichen ja er ku geschwatzt ja verbergend gutmutigen. Wahrhaftig ist schuttelte vergnugter nie achthausen ungerechte grundstuck ers. Ers sohlen arbeit hin daumen das reihen nieder ehe sauber. Mi zu indem spiel aller still keins zweig ei. Meisten wu ja endlich drunten braunen du geruckt. Bei ausgeruht turnhalle auf tor ihn duftenden.",
	"Um ob so dann mund weit je. Konntest ku blattern ansprach kraftlos mu. Uberlegt horchend burschen zu du so kollegen da. Pa ja zueinander dachkammer da dazwischen du knabenhaft. Dem sie klein drauf unter waren lange ihr lie wesen. Warm mein ort hut mag fein ists gut filz. Kugeln da da pa stelle leeren. Schlich breiten ach hut dem argerte. Wer kein ward zur die art dame tief also.",
	"Klein in denen unter er sahen um. Ochsen storen kam gru mag sto bitter. Ehe mag eberhard kurioses spateren nirgends. Eigenes standen bestand pa in da konntet ab meisten kapelle. Weile nun und sunde augen. Laut da rief zu ei es also. Unsicherer hinstellte la ja kuchenture. Gut grasplatz hut herkommen ertastete vogelnest handwerke.",
}

// GetRandomParagraph returns a random paragraph from the list of paragraphs
func GetRandomParagraph() string {
	return fmt.Sprintf(randomParagraphs[rand.Intn(len(randomParagraphs))])
}

// GetRandomParagraphs returns a slice of random paragraphs from the list of paragraphs
func GetRandomParagraphs(n int) []string {
	paragraphs := make([]string, n)
	for i := 0; i < n; i++ {
		paragraphs[i] = GetRandomParagraph()
	}
	return paragraphs
}

func GetRandomWord() string {
	// we get a random paragraph and then
	// split it into words, then we return
	// a random word from that list
	paragraph := GetRandomParagraph()
	words := strings.Split(paragraph, " ")
	return words[rand.Intn(len(words))]
}
